language: cpp
compiler: gcc
sudo: required

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get --qq update
  - sudo apt-get --qq install libstdc++6-4.7-dev  
  - ./install_oclint.sh

script: 
  - ./build.sh
  - ./do_oclint.sh
  - ./travis_oclint
